# Generated by Django 4.1.7 on 2023-04-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('round', models.IntegerField()),
                ('race_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('circuit_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
